# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TakeMeToChurch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TakeMeToChurch
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'TakeMeToChurchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

workspace 'TakeMeToChurch'
